services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cowork_laravel
    ports:
      - "8182:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
  db:
    image: mysql:8.1
    container_name: cowork_mysql
    environment:
      MYSQL_ROOT_PASSWORD: cowork
      MYSQL_DATABASE: cowork
    ports:
      - "3334:3306"
